2021 January updates
moderndive/ModernDive_book pull request #417
Opened 2021-01-29 23:37 UTC by rudeboybert

2021-01-30 00:23 UTC, rudeboybert commented
Hey @ismayc, please hold off on merging into master after your review. I'm still thinking about what to do about deployment

2021-02-04 17:10 UTC, ismayc commented on 92-appendixB.Rmd
> +We, therefore, do not have sufficient evidence to reject the null hypothesis.  Our initial guess that our observed sample proportion was not statistically different the hypothesized proportion has no
```suggestion
We, therefore, do not have sufficient evidence to reject the null hypothesis.  Our initial guess that our observed sample proportion was not statistically different from the hypothesized proportion has not been invalidated.  Based on this sample, we have do not evidence that the proportion of all customers of the large electric utility satisfied with service they receive is different from 0.80, at the 5% level.
```

2021-02-04 17:12 UTC, ismayc commented on 92-appendixB.Rmd
> +The test statistic is a random variable based on the sample data.  Here, we want to look at a way to estimate the population mean difference $\mu_{diff}$.  A good guess is the sample mean difference
Probably best to not hard code here, right?

2021-02-04 17:13 UTC, ismayc commented on 94-appendixD.Rmd
> +**Solution**: Most of the time the gain is a little above zero (the median is 7, meaning gain is above 0 at least 50% of the time), most of the time the gain is between -50 and 50 minutes. There are
This sentence might need some cleaning up since "most of the time" is repeated twice with two different situations.

2021-02-04 17:13 UTC, ismayc requested changes
Just a few comments here. Otherwise it looks good!

2021-02-05 20:37 UTC, merged